### ISSUE TITLE
Appendix code to R

### ISSUE THREAD

**Issue by bebailey** [ProfBailey/machine-learning#1]
There are two papers in the [speiser-project](https://github.com/ProfBailey/machine-learning/tree/master/speiser-project) folder with R code that needs to be translated to actual .R files. Copying and pasting on my machine resulted in a jumbled mess and I expect that will be the case on yours, too.

Please get the pdf code into the corresponding R files and clean it up using [tidy syntax principles](https://style.tidyverse.org/syntax.html#spacing). 

The bimm-tree pdf will include functions for both trees and forests; we only need the tree functions. 

Would be great to have this done in the next week or so.

**Comment by thetonyni** [comment]
Finished! I wasn't able to test out to see whether or not if the functions worked (because I didn't have the dataset they used), but I think the majority should be right! (There were some issues/confusion I had with in the mcart.R with distinguishing between a minus sign and a hyphen mark (wasn't sure if it was subtraction or a line cut-off) I added some comments to the areas where I think there may be issues/bugs!
